AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'coverage/**/*'
    - 'versions/**/*'
    - 'grafana/**/*'

# Style preferences
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

# Metrics
Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'spec/**/*'
    - 'examples/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'examples/**/*'
    - '*.gemspec'

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150

Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'spec/**/*'
    - 'examples/**/*'

# Layout
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'
    - 'examples/**/*'

# Naming
Naming/MethodParameterName:
  AllowedNames:
    - op
    - id
    - v1
    - v2
    - v3
