AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'coverage/**/*'
    - 'versions/**/*'
    - 'grafana/**/*'
    - 'examples/**/*'

# Style preferences
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

# Metrics
Metrics/MethodLength:
  Max: 31
  Exclude:
    - 'spec/**/*'
    - 'examples/**/*'
    - 'bin/**/*'
    - 'benchmarks/**/*'
    - 'lib/decision_agent/versioning/file_storage_adapter.rb'
    - 'scripts/generate_coverage_report.rb'
    - 'lib/decision_agent/dsl/operators/**/*'
    - 'lib/decision_agent/dsl/helpers/**/*'
    - 'lib/decision_agent/monitoring/dashboard_server.rb'
    - 'lib/decision_agent/web/server.rb'

Metrics/BlockLength:
  Max: 99
  Exclude:
    - 'spec/**/*'
    - 'examples/**/*'
    - '*.gemspec'
    - 'lib/decision_agent/web_ui/**/*'
    - 'lib/decision_agent/web/server.rb'

Metrics/ClassLength:
  Max: 322
  Exclude:
    - 'spec/**/*'
    - 'lib/decision_agent/monitoring/dashboard_server.rb'

Metrics/ModuleLength:
  Max: 150
  Exclude:
    - 'lib/decision_agent/dsl/operators/**/*'
    - 'lib/decision_agent/dsl/helpers/**/*'

Metrics/AbcSize:
  Max: 39
  Exclude:
    - 'spec/**/*'
    - 'examples/**/*'
    - 'bin/**/*'
    - 'lib/decision_agent/versioning/file_storage_adapter.rb'
    - 'lib/decision_agent/dsl/operators/**/*'
    - 'lib/decision_agent/dsl/helpers/**/*'
    - 'lib/decision_agent/monitoring/dashboard_server.rb'
    - 'lib/decision_agent/web/server.rb'

# Layout
Layout/LineLength:
  Max: 146
  Exclude:
    - 'spec/**/*'
    - 'examples/**/*'
    - 'decision_agent.gemspec'

# Naming
Naming/MethodParameterName:
  AllowedNames:
    - op
    - id
    - v1
    - v2
    - v3
    - io
    - k
    - v
    - ws

Naming/VariableNumber:
  Enabled: false

Naming/PredicatePrefix:
  Exclude:
    - 'lib/decision_agent/dsl/schema_validator.rb'
    - 'lib/decision_agent/auth/**/*'

Naming/PredicateMethod:
  Exclude:
    - 'spec/**/*'
    - 'lib/decision_agent/dsl/schema_validator.rb'
    - 'lib/decision_agent/audit/logger_adapter.rb'
    - 'lib/decision_agent/conflict_resolution/highest_weight_resolver.rb'
    - 'lib/decision_agent/monitoring/metrics_collector.rb'
    - 'lib/decision_agent/monitoring/alert_manager.rb'
    - 'lib/decision_agent/evaluation_validator.rb'
    - 'lib/decision_agent/auth/**/*'

# Complexity metrics for main library code
Metrics/CyclomaticComplexity:
  Max: 18
  Exclude:
    - 'spec/**/*'
    - 'examples/**/*'
    - 'lib/decision_agent/dsl/operators/**/*'
    - 'lib/decision_agent/dsl/helpers/**/*'
    - 'lib/decision_agent/monitoring/dashboard_server.rb'
    - 'lib/decision_agent/web/server.rb'

Metrics/PerceivedComplexity:
  Max: 16
  Exclude:
    - 'spec/**/*'
    - 'examples/**/*'
    - 'lib/decision_agent/versioning/file_storage_adapter.rb'
    - 'lib/decision_agent/dsl/operators/**/*'
    - 'lib/decision_agent/dsl/helpers/**/*'
    - 'lib/decision_agent/monitoring/dashboard_server.rb'
    - 'lib/decision_agent/web/server.rb'

# Gemspec configuration
Gemspec/DevelopmentDependencies:
  Enabled: false

# Lint
Lint/MissingSuper:
  Exclude:
    - 'examples/**/*'
    - 'lib/decision_agent/audit/logger_adapter.rb'
    - 'lib/decision_agent/evaluators/**/*'
    - 'lib/decision_agent/scoring/**/*'
    - 'lib/decision_agent/versioning/**/*'

Lint/UnusedMethodArgument:
  Exclude:
    - 'examples/**/*'
    - 'spec/**/*'
    - 'lib/decision_agent/web_ui/**/*'
    - 'lib/decision_agent/evaluators/**/*'
    - 'lib/decision_agent/versioning/**/*'
    - 'lib/decision_agent/monitoring/alert_manager.rb'

# Style
Style/ComparableClamp:
  Enabled: false

Style/MultilineBlockChain:
  Exclude:
    - 'spec/**/*'

Lint/IneffectiveAccessModifier:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Metrics/ParameterLists:
  Max: 6
  Exclude:
    - 'lib/decision_agent/dsl/operators/**/*'
    - 'lib/decision_agent/dsl/helpers/**/*'

# Disable FormatStringToken for benchmark files (simple format strings are fine)
Style/FormatStringToken:
  Exclude:
    - 'benchmarks/**/*'
